version: '3'
services:
  miniflux:
    image: miniflux/miniflux:2.0.6
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      #- CREATE_ADMIN=1
      #- ADMIN_USERNAME=admin
      #- ADMIN_PASSWORD=test123
  db:
    image: postgres:10.1
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
